### ISSUE TITLE
System independent directory solutions for #12858

### ISSUE THREAD

**Issue by mayaarguelles** [nyu-ossd-s19/gatsby#1]
i've proposed a basic solution for finding if the current working directory of the project is in an existing git repository but i'm pretty sure this won't hold up across all operating systems. currently i have:
```javascript
// line 34 of /packages/gatsby-cli/src/init-starter.js
let curDir = rootPath

  while (curDir.split(`/`).length > 1) {
    if (existsSync(sysPath.join(curDir, `.git`))) {
      return
    }

    curDir = sysPath.resolve(curDir, `..`)
  }

  if (existsSync(sysPath.join(`.git`))) {
    return
  }

  return await spawn(`git init`, { cwd: rootPath })
```

but i'm pretty sure we'll need to use [path.sep](https://nodejs.org/api/path.html#path_path_sep) (or sysPath.sep, in this case) to check for what the specific path segment separator is and then use that to test ... something like:

```javascript
const pathSep = sysPath.sep(curDir);
const baseSepNum = pathSep  === `/` ? 1 : 2 // if the separator is `/`, one slash represents the root directory, while `\` uses 2 slashes -- so something like `C:\\` represents the root directory

while (curDir.split(pathSep).length > baseSepNum) { ...
```

@ashley @hassan3095 if either of you wants to drop in that functionality that would be great! and then we can run a few tests to see if that works .

(also -- i committed my changes to a new branch: `gatsby-cli-git`)

**Comment by ashley** [comment]
I'll give this a try tomorrow after class 💃

**Comment by ashley** [comment]
@mayaarguelles I added the change, but I can't push to your branch because I'm not a contributor. Can you send the invite for the repo again?

**Comment by mayaarguelles** [comment]
@ashley whooops just added ya
